from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Question(models.Model):
    # We store the genre string directly (e.g. 'dbms')
    genre = models.CharField(max_length=100)
    question = models.TextField()
    # Optional model answer generated by AI
    answer = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.question[:50]

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    rating = models.FloatField()
    user_answer = models.TextField()
    feedback = models.TextField()
    submit_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} - {self.question.id}"